name: Test Documentation deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn 
          cache-dependency-path: docs

      - name: Install dependencies
        run: yarn install
        working-directory: docs
      - name: Test build website
        run: yarn build
        working-directory: docs
